### ISSUE TITLE
UFO: Enemy Unknown (OCS) glitches

### ISSUE THREAD

**Issue by meauxdal** [Optiroc/AGSImager#17]
Little bug report. 

UFO: Enemy Unknown works - it launches and the gameplay seems fine, but the music plays far too slow and the HUD in Battlescape seems to be tinted green. 

I also tried the OCS version launched from Workbench, using the /shared folder to transfer the WHDLoad files directly. It ran the music fine from here - no green tint on the HUD during Battlescape either. It did do some weird flashing in certain transitions, though.

Using MegaAGS-20201116 with its included default config

Directly from the MegaAGS launcher:
https://www.youtube.com/watch?v=5cDBZvskNF4

From Workbench on the same MegaAGS image, using my own WHDLoad files:
https://www.youtube.com/watch?v=MReQBxmDyy8

**Comment by Optiroc** [comment]
Can you check the status of this issue, @meauxdal ?

**Comment by meauxdal** [comment]
Just had a quick test - issue seems to be fully resolved on MegaAGS-20210309 - fresh install with default configuration files. Music is now playing at the correct speed, there is no green tint in the Battlescape HUD. No flashing either, although that only happened with my own WHDLoad files. Thank you @Optiroc !
