### ISSUE TITLE
Dynablaster: Multiplayer not working as intended

### ISSUE THREAD

**Issue by IainMcNulty** [Optiroc/AGSImager#171]
**Steps to Reproduce**
1. Boot up AmigaVision 2023.12.25 on MiSTer.
2. Select Dynablaster.
3. Select 'Battle' from the Main Menu.
4. Select either Normal or Skull Mode.
5. Select 2 Players.
6. Select 3 Win Match.
7. Play as normal.

**Result**
Both players will spontaneously self-destruct before a minute has passed. This does not occur with the non-AmigaVision version of the title.

**Comment by limi** [comment]
Interesting. I looked at the WHDLoad bug reports on Dynablaster, and nothing like that has been reported. Maybe report it upstream? We just use the standard WHDLoad setup, nothing custom for AmigaVision.

People have been good at fixing WHDLoad bugs lately, worth filing an issue:

http://mantis.whdload.de

**Comment by limi** [comment]
Reported here: http://mantis.whdload.de/view.php?id=6502

I assume that by “non-AmigaVision version” you mean the ADF version? If not let me know. We just use the standard WHDLoad setup, nothing custom for this game.

**Comment by limi** [comment]
Fantastic, thank you! Will update the WHDLoad bug report, and we may also be able to supply a different default setting in AmigaVision if it is exposed as an argument.

**Comment by limi** [comment]
Looks like there is a new version available: https://www.whdload.de/mantis/view.php?id=6502
