### ISSUE TITLE
A few older games launch with audio filtering on, even with Auto LED set

### ISSUE THREAD

**Issue by movisman** [Optiroc/AGSImager#18]
Hi!

As discussed, a few games like Hostages, Shufflepuck Cafe and Persian Gulf Inferno (just a small number I found so far) - when these are launched the audio is filtered, even with Auto LED set.

You have to explicitly turn the audio filter to off in MiSTer to make the audio clearer.

Usually, in Auto LED mode, most games will launch without the filter, and then the filter kicks in when needed (driving through a tunnel in Lotus 2 for example).

Limi mentioned some older games do not turn the filter off by default, causing this issue.

Just logging this here as Optiroc was possibly going to investigate - perhaps there is a WHDload default which can be set on games like these to turn the audio filter off by default.

It is a very minor issue - if not worthy of investigation just close it off!

Cheers

**Comment by limi** [comment]
WHDLoad does have a NoFilter option, which also respects when the game/app wants to turn it back on explicitly. So we should probably make that the default.

**Comment by Optiroc** [comment]
Agreed!

**Comment by movisman** [comment]
Hi both,

That sounds great if WHDload has a NoFilter option, which respects when the game/app wants to turn it back on.

That means I can leave the audio filter in MiSTer set to 'Auto LED', have unfiltered audio until such time when a game demands it.

Sounds like the perfect solution if it is possible.

Thanks!
