### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by ReadyPlayer29** [Optiroc/AGSImager#28]
Could you ad to the whdload.prefs file the PRELOAD option.

Should then force any games that dont have it in .info files to preload.

From what i understand of whdload this should reduce os swapping and may make somethings run smoother

**Comment by Optiroc** [comment]
Everything is already using PRELOAD via the generated run-scripts: https://github.com/Optiroc/AGSImager/blob/master/ags_build.py#L361

But, since it’s used across the board we should probably add it to the main config instead.
