### ISSUE TITLE
Game Issue - Apidya - Crash on stage 2

### ISSUE THREAD

**Issue by M-Walrus** [Optiroc/AGSImager#30]
I've gotten to the same point with the original and hacked versions of Apidya, and both of them crash at a certain point of stage 2 when an area with water ends.  

This is the error from the crash:

Exception "Illegal Instruction" ($10) at $2F85 occured.

**Comment by Optiroc** [comment]
Good find! Now the question is if it’s an issue with the Minimig 020 core or the WHDL slave. It’s likely the former, but in any case I’ll add an issue note.
