### ISSUE TITLE
The Fall demo

### ISSUE THREAD

**Issue by bfbiii** [Optiroc/AGSImager#31]
Obviously there are tons of modern demos worth adding. This is just a suggestion that the HD installable version of The Fall be added. It can be downloaded here.
[http://deadliners.net/thefall/TheFallFinal.zip](url)

**Comment by Optiroc** [comment]
Oh, I quickly looked at this at one point when I started to add non-whdl content and thought "oh, 2 ADFs, well that's a trackmo – only hope is that someone makes a WHDL slave then". Apparently not! Thanks!
