### ISSUE TITLE
Add Metal Gear port

### ISSUE THREAD

**Issue by limi** [Optiroc/AGSImager#32]
https://hoffman.home.blog/metal-gear/

**Comment by Optiroc** [comment]
Oh, nice!

**Comment by Optiroc** [comment]
Done https://github.com/Optiroc/AGSImager/commit/5594cdb71d714878ca21952dccb890fa518c3941#diff-e6117371ecbed5ef4890b5e4816daea90b60ce9fd707208b24d7a5e414fe72f0R4774
