### ISSUE TITLE
The Great Giana Sisters not set to PAL?

### ISSUE THREAD

**Issue by Negsol** [Optiroc/AGSImager#35]
The Great Giana Sisters is not set to PAL? - Compare the music Chris Hülsbeck published on cd - ntsc definitely plays the music to fast .. - Great work anyhow - please keep improving!

**Comment by Optiroc** [comment]
I may be the minority here, but I think this is a game that gets much more tolerable to play at 60Hz. You do have the point with the music certainly being composed for 50Hz though... But in this case I went with 60Hz as default anyway.
