### ISSUE TITLE
Chronological listing of disk mags

### ISSUE THREAD

**Issue by limi** [Optiroc/AGSImager#43]
Can we have a subcategory in disk mags for “Chronological”?

There’s a lot of demo scene drama that references older releases, would be cool to be able to read them in chronological order 😜 

Of course, it would require us to add more precise dates to those entries, but I’m happy to do the legwork on that.

**Comment by Optiroc** [comment]
Done in f421943c5404a9de5b11c8fb4cca7be1e70a0668
