### ISSUE TITLE
joe & mac caveman ninja image shifted upwards like "All New World of Lemmings" was before latest update

### ISSUE THREAD

**Issue by Akoi89** [Optiroc/AGSImager#48]
Hi,

I noticed that in "Joe & Mac caveman ninja" the image is shifted upwards (which cuts off the top of the screen) like "All New World of Lemmings" did before the latest update. (which I reported in the forums and you were able to fix it) seems to be maybe fine before the gameplay starts?

Thank you and I love the work you guys have done. I am testing quite a few games since the latest update, I assume this is the best place to post issues for you guys?

**Comment by Optiroc** [comment]
@Akoi89 Posting issues here works well 👍 

I tweaked the viewport for Joe & Mac in this commit: c0c8fd487744910c9167aa9ad393053a8a348720

Curiously the previous setting was an untouched full PAL viewport, but it was moved way up compared to the standard. I set it up with a 5X viewport instead. Pretty bad game, this! :)
