### ISSUE TITLE
Worldcharts 1-8 & 9-15 missing

### ISSUE THREAD

**Issue by limi** [Optiroc/AGSImager#58]
Maybe they are trackloaders? Must investigate 😊

**Comment by Optiroc** [comment]
Adding issues 1-5. Issue 6 isn’t NDOS, but there’s no regular file table either. Checking the rest as I go...

**Comment by Optiroc** [comment]
7 is a regular binary. 8 uses the same scheme as 6.

**Comment by Optiroc** [comment]
Added all issues with regular filesystems in de056262fbefa0806c293c8309948796997e8f8e
