### ISSUE TITLE
Update California Games Crack Intro WHDLoad Slave to 1.1

### ISSUE THREAD

**Issue by retrofun** [Optiroc/AGSImager#63]
Update California Games Crack Intro WHDLoad Slave to 1.1.

After 20 years finally a proper WHDLoad Slave! :wink:
http://mantis.whdload.de/view.php?id=5686

http://www.whdload.de/ctros/WorldOfWonders_CaliforniaG.html

**Comment by Optiroc** [comment]
Great stuff 💯 

Database updated and it should be included in future builds.
