### ISSUE TITLE
Add Paradox’ Arabian Nights cracktro

### ISSUE THREAD

**Issue by limi** [Optiroc/AGSImager#65]
This is an all-time classic intro, IMO — attached.

Seems to play nice with the OS, I saw no artifacts by running it directly (although it will need to be switched to PAL for correct music speed)

**Comment by limi** [comment]
[Paradox-CrArabianNights.zip](https://github.com/Optiroc/AGSImager/files/9438525/Paradox-CrArabianNights.zip)

**Comment by Optiroc** [comment]
Added [this version](http://janeway.exotica.org.uk/release.php?id=6420) instead, which was the first use of this intro that I could find.

Fixed in f30b2bf6be75a230bee0f6343aa04f8cfbe4e602
