### ISSUE TITLE
Add Super Sprint

### ISSUE THREAD

**Issue by limi** [Optiroc/AGSImager#66]
Can be downloaded from http://meynaf.free.fr/pr/index_en.html — no WHDL container, but is a modern port. Looks like 5×PAL or NTSC mode would be in order, too.

**Comment by limi** [comment]
Note: Ctrl-C to quit the game.

**Comment by Optiroc** [comment]
Added, but will go through the viewport settings for all the homebrew conversions before commiting.

**Comment by Optiroc** [comment]
I postponed fixing viewport settings to another day. :)

Done in 5f2ba4c07b36f04da89ce36192fd521a8bc00980
