### ISSUE TITLE
Adding games issue

### ISSUE THREAD

**Issue by theenemy-thd** [Optiroc/AGSImager#68]
On older versions I was able to add the files to dh1:whdload/letter and add files needed (iff,run and txt) in dh0:ags all/letter with the all games directory and when booted back up it would show the new added game

This doesnt happen now which is a shame as I have purchased games (devils temple, turbo sprint) which I enjoyed from running via megaAGS

**Comment by Optiroc** [comment]
Yes, there is a new directory cache feature that throws a wrench into a manually edited setup like yours. 

The solution is to either remove the `.dir` file in the directory you want to edit. Alternatively you can edit the dir file, it’s just a text file.

**Comment by theenemy-thd** [comment]
I tried editing the .dir last night and it just exited and  threw up a load of characters ... I will try deleting like you mentioned .. thanks
