### ISSUE TITLE
Include RTPatch to switch requesters to all use ReqTools

### ISSUE THREAD

**Issue by limi** [Optiroc/AGSImager#71]
This was a pretty common thing to do back in the day; you want your file requesters to behave the same in every app. ReqTools includes a tool to do this, and I have applied it on the A500HD and A600HD setups successfully. 

CED is a lot better when the file requester is a modern one that supports e.g. clicking the right button for the volume list, and behaves consistently with every other app.

Archive:
http://aminet.net/package/util/libs/ReqToolsUsr

Ignore the installer and library since `reqtools.library` is already part of the image creation. The only thing needed is copying `RTPatch` to `C:` and adding this into`s:user-startup`:

```C:RTPatch >NIL:```

**Comment by Optiroc** [comment]
Done. I experimented with another requester patch for some reason before (I believe it was because some of the Maxis game had issues). Reverted back to rtpatch now.
